spring:
  application:
    name: "MainApplication32Bit"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  cache:
    type: ${SPRING_CACHE_TYPE}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_EMAIL_USERNAME}
    password: ${APP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  coordinator:
    subscriber-bindings:
      - name: "RestSubscriber"
        enabled: ${REST_SUBSCRIBER_ENABLED:true}
        configName: "rest-config.yaml"
        jarName: "rest-subscriber-0.0.1.jar"
        classPath: "com.berkepite.RateDistributionEngine.RestSubscriber.RestSubscriber"
        configClassPath: "com.berkepite.RateDistributionEngine.RestSubscriber.RestConfig"
      - name: "TCPSubscriber"
        enabled: ${TCP_SUBSCRIBER_ENABLED:true}
        configName: "tcp-config.yaml"
        jarName: "tcp-subscriber-0.0.1.jar"
        classPath: "com.berkepite.RateDistributionEngine.TCPSubscriber.TCPSubscriber"
        configClassPath: "com.berkepite.RateDistributionEngine.TCPSubscriber.TCPConfig"
    rates: ${APP_RATES}
  rate-calculation-strategy: ${APP_RATE_CALCULATION_STRATEGY}
  rate-calculator-path: ${APP_RATE_CALCULATOR_PATH}
  kafka:
    raw-rate-topic: "raw_rates"
    calc-rate-topic: "calc_rates"
  email:
    group-file: ${APP_EMAIL_GROUPS}
    enabled: ${APP_EMAIL_ENABLED}