spring:
  application:
    name: "MainApplication32Bit"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:debug}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  cache:
    type: ${SPRING_CACHE_TYPE}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

app:
  coordinator:
    subscriber-bindings:
      - name: "RestSubscriber"
        enabled: ${REST_SUBSCRIBER_ENABLED:true}
        configName: "rest-config.yaml"
        jarName: "rest-subscriber-0.0.1.jar"
        classPath: "com.berkepite.RateDistributionEngine.RestSubscriber.RestSubscriber"
        configClassPath: "com.berkepite.RateDistributionEngine.RestSubscriber.RestConfig"
      - name: "TCPSubscriber"
        enabled: ${TCP_SUBSCRIBER_ENABLED:true}
        configName: "tcp-config.yaml"
        jarName: "tcp-subscriber-0.0.1.jar"
        classPath: "com.berkepite.RateDistributionEngine.TCPSubscriber.TCPSubscriber"
        configClassPath: "com.berkepite.RateDistributionEngine.TCPSubscriber.TCPConfig"
    rates: "USD_TRY,EUR_USD,GBP_USD"
  rate-calculation-strategy: ${APP_RATE_CALCULATION_STRATEGY}
  rate-calculator-path: ${APP_RATE_CALCULATOR_PATH}
  kafka:
    raw-rate-topic: "raw_rates"
    calc-rate-topic: "calc_rates"