name: engine-cluster
services:
  rate-distribution-engine:
    image: luieitalian/rate-distribution-engine
    container_name: rate-distribution-engine
    networks:
      - network
    volumes:
      - engine_logs_volume:/app/logs
      - ./subscribers:/app/subscribers
      - ./rate_calculators:/app/rate_calculators
      - ./application-config.yaml:/app/application-config.yaml:ro
      - ./rates.csv:/app/rates.csv:ro
    depends_on:
      rest-platform:
        condition: service_started
      tcp-platform:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: debug
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_RATE_CALCULATION_STRATEGY: PYTHON
      APP_RATE_CALCULATOR_PATH: "/app/rate_calculators/py-calc.py"
      APP_RATES: "/app/rates.csv"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      TCP_SUBSCRIBER_ENABLED: true
      REST_SUBSCRIBER_ENABLED: true

  tcp-platform:
    image: luieitalian/tcp-platform-standalone
    container_name: tcp-platform-standalone
    volumes:
      - ./initial_data_tcp.json:/app/initial_data.json:ro
    networks:
      - network
    environment:
      TCP_SERVER_USER: client
      TCP_SERVER_PASSWORD: 2345
      TCP_SIMULATOR_UPDATE_INTERVAL: 2000
      TCP_SERVER_TOTAL_STREAMS: 100
      TCP_SERVER_STREAM_INTERVAL: 2100
      APPLICATION_PROFILE: prod
      SIMULATOR_ENABLED: true
      SIMULATOR_INTENSITY: med
    ports:
      - "2000:8080"

  rest-platform:
    image: luieitalian/rest-platform
    container_name: rest-platform
    volumes:
      - ./initial_data_rest.json:/app/initial_data.json:ro
    networks:
      - network
    environment:
      REST_SERVER_USER: client
      REST_SERVER_PASSWORD: 1234
      REST_REQUEST_LIMIT: 100
      SPRING_PROFILES_ACTIVE: prod
      SIMULATOR_ENABLED: true
      SIMULATOR_INTENSITY: med
    ports:
      - "1000:8080"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - network
    ports:
      - "6379:6379"
#
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    networks:
#      - network
#    environment:
#      POSTGRES_USER: debug_user
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: backend

networks:
  network:
    driver: bridge

volumes:
  engine_logs_volume:
