name: rest_subscriber
classPath: com.berkepite.RateDistributionEngine.RestSubscriber
className: RestSubscriber
url: http://rest-platform:8080
port: 8080
username: client
password: 1234
includeRates:
excludeRates:
requestInterval: 2000
requestRetryLimit: 5
healthRequestRetryLimit: 5
